### ISSUE TITLE
Fail to create incident when 'details: not null'

### ISSUE THREAD

**Issue by namachieli** [StackStorm-Exchange/stackstorm-pagerduty#13]
So I'm running into an issue where I am unable to create an incident when the field for "details" is anything other than 'null'. I've even tried using a single word, no spaces or special characters, but from an action chain and manually from the gui.

This is what im getting from python;
```
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 259, in <module>
    obj.run()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 155, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/pagerduty/actions/launch_incident.py", line 16, in run
    result = self.pager.Event.create(data=payload)
  File "/opt/stackstorm/virtualenvs/pagerduty/lib/python2.7/site-packages/pypd/models/event.py", line 42, in create
    cls.validate(data)
  File "/opt/stackstorm/virtualenvs/pagerduty/lib/python2.7/site-packages/pypd/models/event.py", line 33, in validate
    assert isinstance(event_info['details'], dict)
AssertionError
```
Looking at the output from st2 it appears that the correctly formatted data is being sent to [launch_incident.py](https://github.com/StackStorm-Exchange/stackstorm-pagerduty/blob/master/actions/launch_incident.py) but based on the error in python it seems like it doesn't like something.

Doesn't appear like im doing something wrong and that maybe something about this package needs to be updated.

If I leave 'details' null, the incident opens fine (just with no useful info)

**Comment by LindsayHill** [comment]
@namachieli I wonder if this is the fix https://github.com/StackStorm-Exchange/stackstorm-pagerduty/pull/12/files ?
Could you try making that change locally, and see if that works?

**Comment by LindsayHill** [comment]
Addressed by https://github.com/StackStorm-Exchange/stackstorm-pagerduty/pull/12
